### ISSUE TITLE
YAML version of configuration

### ISSUE THREAD

**Issue by sovetski** [softavis/flysystem-cloudflare#1]
Hi,

First thank you for this great work

Can you please provide the YAML version of your configuration like we have here? https://github.com/thephpleague/flysystem-bundle/blob/3.x/docs/4-using-lazy-adapter-to-switch-at-runtime.md

Thanks

**Comment by naskoff** [comment]
Hi, @sovetski , It's not great, but it is honest work. :)
I edited the README file and added a usage example with Symfony.

**Comment by sovetski** [comment]
Thank you @naskoff, but it did not work for me (Symfony 6).
I created a pull request with the config which works: https://github.com/softavis/flysystem-cloudflare/pull/2

**Comment by naskoff** [comment]
Hi @sovetski , Have you tried adjusting the configuration from the readme file?
The problem with your configuration, as far as I can see:
- definition of Softavis\Flysystem\Cloudflare\Client does not have additional env's ? 
- The library needs to configure HttpClient with auth_bearer authentication already. Because of this, I use scoped client references in Readme.

**Comment by sovetski** [comment]
> Hi @sovetski , Have you tried adjusting the configuration from the readme file? The problem with your configuration, as far as I can see:
> 
> * definition of Softavis\Flysystem\Cloudflare\Client does not have additional env's ?
> * The library needs to configure HttpClient with auth_bearer authentication already. Because of this, I use scoped client references in Readme.

I tried every possibilities but did not work 😕 I added some description to my PR: https://github.com/softavis/flysystem-cloudflare/pull/2#issue-2229136714

To simplify the package's usage, I modified the Client.php's constructor.
In the current version, the usage is:

```php
$client = new Client(HttpClient::createForBaseUri(sprintf(CLOUDFLARE_URL, CLOUDFLARE_ACCOUNT_ID), [
    'auth_bearer' => CLOUDFLARE_API_KEY,
]));
```

With my modified version:

```php
$client = new Client(CLOUDFLARE_URL, CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_API_KEY);
```

In Client.php, the constructor now is:

```php
 public function __construct(string $url, string $accountId, string $apiKey)
{
    $this->client = HttpClient::createForBaseUri(sprintf($url, $accountId), [
        'auth_bearer' => $apiKey,
    ]);
}
```

So in my flysystem.yaml, It is more simple to configure it

```yaml
services:
    cloudflare_client:
        class: Softavis\Flysystem\Cloudflare\Client
        arguments:
            $url: "%env(CLOUDFLARE_URL)%"
            $accountId: "%env(CLOUDFLARE_ACCOUNT_ID)%"
            $apiKey: "%env(CLOUDFLARE_API_KEY)%"
    cloudflare_adapter:
        class: Softavis\Flysystem\Cloudflare\CloudflareAdapter
        arguments:
            - "@cloudflare_client"
```

I'm putting my solution here to help people who might have similar issues; it might provide a clue.
