### ISSUE TITLE
Account hash and variant names are missing

### ISSUE THREAD

**Issue by sovetski** [softavis/flysystem-cloudflare#5]
Hi,

On the new configuration for YAML, the account hash and variant name are missing, so the returned public url is: `https://imagedelivery.net//myfilename.png/` the account hash and variants are missing.

I tried with `public_url`:

```yaml
flysystem:
    storages:
        images.storage.cloudflareimages:
            adapter: "cloudflare_adapter"
            public_url: "https://imagedelivery.net/%env(CLOUDFLARE_ACCOUNT_HASH)%/%env(CLOUDFLARE_VARIANT_NAME)%/"
```

But in this case, the variant name is before the file name which is incorrect. It returns `https://imagedelivery.net/HASH/VARIANT/myfilename.png`

I also tried it but not worked:

```yaml
flysystem:
    storages:
        images.storage.cloudflareimages:
            adapter: "cloudflare_adapter"
            options:
                accountHash: "account_hash_here"
                variantName: "variant_name_here"
```

**Comment by naskoff** [comment]
Hi @sovetski ,these options are not supported by the abstraction of league/flysystem-bundle, but I suggest using a sample twig filter/function to work with that.
For that, first bind these options in services.yaml

```
        bind:
            string $accountHash: '%env(CLOUDFLARE_ACCOUNT_HASH)%'
            string $variantName: '%env(CLOUDFLARE_VARIANT_NAME)%'
```
and create twig function/filter
```
class AppExtensionRuntime implements RuntimeExtensionInterface
{
    public function __construct(
        private readonly FilesystemOperator $defaultStorage,
        private readonly string $accountHash,
        private readonly string $variantName,
    )
    {
    }

    public function imageUrl(string $path, ?string $variantName = null): string
    {
        return $this->defaultStorage->publicUrl($path, [
            'accountHash' => $this->accountHash,
            'variantName' => $variantName ?? $this->variantName,
        ]);
    }
}
```

In that way, every time you need show URL of image just use twig filter like that
`entity.image|imageUrl`
or with specific variant name
`entity.image|imageUrl('thumb')`
and so on.

**Comment by sovetski** [comment]
@naskoff thank you for your time and the example provided! What do you think about my proposal? It looks like in AWS3 official adapter, the `bucket` is configured from adapter: https://github.com/thephpleague/flysystem-aws-s3-v3/blob/3.x/AwsS3V3Adapter.php

As the account hash and variant is the part of CloudFlare, we can pass it directly to `CloudflareAdapter`?

I modified it like this (and it works):

In `CloudflareAdapter.php`:

```php
private $client;

private $options; // <--- ADDED

public function __construct(Client $client, array $options = [])
 {
        $this->client = $client;
	$this->options = $options; // <--- ADDED
 }
```

and the `publicUrl` method:

```php
public function publicUrl(string $path, Config $config): string
{
     return strtr('https://imagedelivery.net/{accountHash}/{path}/{variant}', [
          '{accountHash}' => $this->options['accountHash'],
          '{path}' => $path,
          '{variant}' => $this->options['variantName']
     ]);
}
```

or to keep the backward compatibility:
```php
public function publicUrl(string $path, Config $config): string
{
     return strtr('https://imagedelivery.net/{accountHash}/{path}/{variant}', [
          '{accountHash}' => $config->get('accountHash') ?? $this->options['accountHash'],
          '{path}' => $path,
          '{variant}' => $config->get('variantName') ?? $this->options['variantName'],
     ]);
}
```

And my YAML config:
```yaml
services:
    cloudflare_adapter:
        class: 'Softavis\Flysystem\Cloudflare\CloudflareAdapter'
        arguments:
            - "@cloudflare_client"
            - accountHash: "%env(CLOUDFLARE_ACCOUNT_HASH)%"
              variantName: "%env(CLOUDFLARE_VARIANT_NAME)%"
```
